### ISSUE TITLE
The provider doesn't load under Orleans January update

### ISSUE THREAD

**Issue by remusrg** [OrleansContrib/OrleansBlobStorageProvider#6]
Do you mind rebuilding this with 1.0 maybe and regenerating the nuget package? Not sure what the issue is...

In the silo log:

[2015-01-28 18:30:19.864 GMT     4	INFO   	100000	AssemblyLoader.Silo	127.255.0.1:11111]	User assembly ignored: D:\Dev\ETG\UserBots\UserBots.Cloud\csx\Debug\roles\UserBots.WorkerRole\approot\Orleans.StorageProvider.Blob.dll
	* An assembly dependency [Orleans, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Could not load file or assembly 'Orleans, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] could not be loaded: 0	

The exception stack trace is:  

[2015-01-28 18:30:22.606 GMT     4     ERROR            100105  OrleansSiloHost 127.255.0.1:11111]         !!!!!!!!!! ERROR starting Orleans silo name=UserBots.Cloud.UserBots.WorkerRole_IN_0 Exception=System.AggregateException: One or more errors occurred. ---> Orleans.Runtime.OrleansException: Provider of type Orleans.StorageProvider.Blob.BlobStorageProvider name BlobStore was not loaded.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__16()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
---> (Inner Exception #0) Orleans.Runtime.OrleansException: Provider of type Orleans.StorageProvider.Blob.BlobStorageProvider name BlobStore was not loaded.
   at Orleans.Providers.ProviderLoader`1.ValidateProviders()
   at Orleans.Providers.ProviderLoader`1.LoadProviders(IDictionary`2 configs, IProviderManager providerManager)
   at Orleans.Runtime.Storage.StorageProviderManager.LoadStorageProviders(IDictionary`2 configs)
   at Orleans.Runtime.Silo.<DoStart>b__16()
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()<---

**Comment by richorama** [comment]
Will do!

-----Original Message-----

**Comment by remusrg** [comment]
Thank you! I made the wrong assumption that if you renamed the assemblies as per 1.0 (IProvider vs IOrleansProvider) it would work under Orleans 1.0 but for some reason it doesn't :(

Thank you!
Remus

Date: Wed, 28 Jan 2015 11:08:38 -0800

**Comment by richorama** [comment]
The Orleans team haven't released 1.0.0 yet, they're still working on some of the detail, so I'll wait for that release first.

**Comment by gabikliot** [comment]
Richard, it will be the same code as the master branch. No significant changes. We are just finalizing the binary signing process. So anything that works for master should work for 1.0.0.

**Comment by richorama** [comment]
Fixed by #8
